language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master
  - gh-pages

# install grunt globally
before_install:
  - npm install -g npm@2
  - npm install -g grunt-cli
  - npm install -g bower

# install dev dependencies
install:
  - npm install
  - bower install

before_script:
# remove dist folder from .gitignore file
  - echo 'remove dist folder from .gitignore'
  - sed -i '/dist=/d' .gitignore > .gitignore
  - grunt test
  - grunt build

script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Travis CI"
  - git remote set-url origin https://malteahrens:${GH_TOKEN}@github.com/malteahrens/vita
  - git subtree split --prefix dist -b gh-pages # create a local gh-pages branch containing the splitted output folder
  - git push -f origin gh-pages:gh-pages # force the push of the gh-pages branch to the remote gh-pages branch at origin
  - git branch -D gh-pages # delete the local gh-pages because you will need it: ref
  
env:
  global:
    # this is for Travis to be able to push to github to assemble gh-branch
    - secure: "P0SFVXYMJhNb3dX/Hx4rxjL/toViP0Vo0yXbMK/vwOsSrixkU84ltMGykBYTUztdAFJvsO0xrhKsdPbBmdjEF48emrmoymknxKYPIJ6NL1N6fy0EUoE6o7vBX+agthD/uhSNCJgXRK+giqxP5Htz3BkrU9VgdFdVrSqU9bsm4Bc="