language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master

# install grunt globally
before_install:
  - npm install -g grunt-cli

# install dev dependencies
install:
  - npm install
  - grunt build

before_script:

env:
  global:
    # this is for Travis to be able to push to github to assemble gh-branch
    - secure: "eDBjS1tFGZRbvpmxC2V0TrYGY+RW8dtwLROCDRpcF7KpU15KWJBwJzlCoPkWezxMubfhhOfdQdYPd+ZEHdfcrJD0YM0qmDDEGce5NZfH4wp5JAQxgS8WSoKRvRnFpATza3f/nnyXCJrOgc/tVlU5EGdEe/Bg/qk1uITd/AWomjY="