language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master
  - gh-pages

# install grunt globally
before_install:
  - npm install -g npm@2
  - npm install -g grunt-cli
  - npm install -g bower

# install dev dependencies
install:
  - npm install
  - bower install
  - sudo apt-get install gdal-bin

before_script:
# remove dist folder from .gitignore file
  - echo 'remove dist folder from .gitignore'
  - sed -i '/dist=/d' .gitignore > .gitignore
  - grunt test
  - grunt build
# generate vector tiles
  - npm install tilelive-bridge

script:
# this script branches the dist folder to the gh-pages branch
  - ogr2ogr --version
  - ogr2ogr -f 'GEOJSON' dist/PasingWlan.geojson app/data/PasingWlan.vrt
  - node ./deploy/scripts/Geojson2VectorTiles.js
  - ./deploy.sh
  
env:
  global:
    # this is for Travis to be able to push to github to assemble gh-branch
    - secure: "P0SFVXYMJhNb3dX/Hx4rxjL/toViP0Vo0yXbMK/vwOsSrixkU84ltMGykBYTUztdAFJvsO0xrhKsdPbBmdjEF48emrmoymknxKYPIJ6NL1N6fy0EUoE6o7vBX+agthD/uhSNCJgXRK+giqxP5Htz3BkrU9VgdFdVrSqU9bsm4Bc="