language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master
  - gh-pages

# install grunt globally
before_install:
  - npm install -g npm@2
  - npm install -g grunt-cli
  - npm install -g bower

# install dev dependencies
install:
  - npm install
  - bower install
  - sudo apt-get install gdal-bin

before_script:
# remove dist folder from .gitignore file
  - echo 'remove dist folder from .gitignore'
  - sed -i '/dist=/d' .gitignore > .gitignore
  - grunt test
  - grunt build
# generate vector tiles
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-get install -y libstdc++6
# node-mapnik
  - npm install mapnik@3.x
# node-mbtiles (alternative to node-mapnik)
  - npm install mbtiles
# sqlite
  - npm install sqlite3
  - npm install node-sqlite3

script:
# this script branches the dist folder to the gh-pages branch
  - node ./deploy/scripts/Geojson2VectorTiles.js

  # Convert wigle wifi sqlite db to different geojson flavours...
  - node ./deploy/scripts/sqlite2geojson.js

  # Clip geojson to Pasing area and copy the result to the dist dir to make it available in the app
  - ogr2ogr --version
  #- ogr2ogr -f 'GEOJSON' dist/data/geojson/PasingWlan_BestLatLon.geojson app/data/PasingWlan_BestLatLon.vrt
  #- ogr2ogr -f 'GEOJSON' dist/data/geojson/PasingWlan_Centroid.geojson app/data/PasingWlan_Centroid.vrt
  #- ogr2ogr -f 'GEOJSON' dist/data/geojson/PasingWlan_PasingWlan_DifVector.geojson app/data/PasingWlan_DifVector.vrt

  # Copy dist folder to gh-pages branch
  - ./deploy/scripts/github.sh
  
env:
  global:
    # this is for Travis to be able to push to github to assemble gh-branch
    - secure: "P0SFVXYMJhNb3dX/Hx4rxjL/toViP0Vo0yXbMK/vwOsSrixkU84ltMGykBYTUztdAFJvsO0xrhKsdPbBmdjEF48emrmoymknxKYPIJ6NL1N6fy0EUoE6o7vBX+agthD/uhSNCJgXRK+giqxP5Htz3BkrU9VgdFdVrSqU9bsm4Bc="