language: android

branches:
  only:
  - mobile

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools

    # The SDK version used to compile your project
    - android-22

# install npm
before_install:
  - nvm install 0.12
  - npm install phonegap -g

script:
  - phonegap create android com.example.hello HelloWorld
  - cd android
  - phonegap platform add android
  #- phonegap build
  - pwd

  # copy apk to release folder
  - cd ..
  - sh ./deploy/scripts/github.sh

env:
  global:
    # this is for Travis to be able to push back to github
    - secure: "P0SFVXYMJhNb3dX/Hx4rxjL/toViP0Vo0yXbMK/vwOsSrixkU84ltMGykBYTUztdAFJvsO0xrhKsdPbBmdjEF48emrmoymknxKYPIJ6NL1N6fy0EUoE6o7vBX+agthD/uhSNCJgXRK+giqxP5Htz3BkrU9VgdFdVrSqU9bsm4Bc="