language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master
  - gh-pages

# install grunt globally
before_install:
  - npm install -g grunt-cli
  - npm install -g bower

# install dev dependencies
install:
  - npm install
  - bower install

script:
  - grunt build
  - git remote set-url origin https://malteahrens:${GH_TOKEN}@github.com/malteahrens/malteahrens.github.io.git
  - git checkout --orphan gh-pages # go to the gh-pages branch
  - git add ./app/* # bring gh-pages up to date with master
  - git commit -m "GitHub Pages Site" # commit the changes
  - git push -u origin gh-pages
  - git checkout master # return to the master branch

env:
  global:
    # this is for Travis to be able to push to github to assemble gh-branch
    - secure: "P0SFVXYMJhNb3dX/Hx4rxjL/toViP0Vo0yXbMK/vwOsSrixkU84ltMGykBYTUztdAFJvsO0xrhKsdPbBmdjEF48emrmoymknxKYPIJ6NL1N6fy0EUoE6o7vBX+agthD/uhSNCJgXRK+giqxP5Htz3BkrU9VgdFdVrSqU9bsm4Bc="